### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by axelson**
Figured it would be nicer to prepare a PR that will support 0.6.0 instead of just asking for it to be released :) Feel free to adjust things if necessary (or let me know what needs adjusting).

### CODE REVIEW

**Comment by benkirzhner** [comment]
Thanks for the PR, @axelson! It looks like updating the list broke the build because of a few tests that rely on some removed rules for `githubcloud.com`. I'll try rebasing this with a different set of test rules.

**Comment by axelson** [comment]
Okay, sounds good!

**Comment by bkirz** [comment]
These commits has been merged as part of #29 and published. Thanks again!

**Comment by axelson** [comment]
Great, thanks!

**Pull request closed without merging**
